### ISSUE TITLE
FR: docker compose file with i2p

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [liamcottle/reticulum-meshchat#84]
Hi,

I think it would be neat if the docker compose could integrate a commented code for how to also start i2p.

Here's the link to the official [i2p on docker](https://geti2p.net/en/download/docker) doc.

Something like that:

```yaml

  i2p:
    # source: https://geti2p.net/en/download/docker
    # 1. The only port you have to expose is the one leading to
    # 12345. To do so, replace the three CHANGEME below
    # by a random port 1024 and 65535 and make sure it
    # supports both UDP and TCP. Dont forget to uncomment those llines
    # 2. Browser to 127.0.0.1:7657 to configure your i2p setup.
    # Note: i2p is not fast to get peers so wait up to 30 minutes
    # before investigating potential issues.
    image: geti2p/i2p
    volumes:
        - ./data/i2p:/i2p/.i2p
    ports:
      # - 127.0.0.1:4444:4444/tcp  # HTTP proxy if you want to browser
      # - 127.0.0.1:4445:4445/tcp  # Same but HTTPS
      - 127.0.0.1:7657:7657  # router console
      # - CHANGEME:12345/tcp  # I2NP protocol
      # - CHANGEME:12345/udp  # I2NP protocol
    environment:
      - EXT_PORT=CHANGEME
    cpus: 2                        # tune according to your system & preferences
    mem_limit: 2048m               # tune according to your system & preferences
    restart: always
```
